// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-attributes
// RUN: %clang_cc1 -triple riscv32 -moverlay -emit-llvm %s -o - \
// RUN:    | FileCheck %s

// CHECK-LABEL: @test_overlay_func(
// CHECK-SAME: #0
// CHECK: attributes #0 = {
// CHECK-SAME: "overlay"
int __attribute__((overlay)) test_overlay_func(void) {
  return 5;
}
